services:

  nginx:
    container_name: SAE401-nginx
    image: nginx:latest
    ports:
      - "8787:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - uploads:/var/www/html/public/uploads
    depends_on:
      - php

  php:
    container_name: SAE401-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - uploads:/var/www/html/public/uploads
    working_dir: /var/www/html
    user: www-data

  mysql:
    container_name: SAE401-mysql
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/lego_store.sql:/docker-entrypoint-initdb.d/lego_store.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lego_store

  phpmyadmin:
    container_name: SAE401-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8788:80"
    depends_on:
      - mysql

  mailhog:
    container_name: SAE401-mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database:
  uploads: