nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8090']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/':  # Applique CORS à toutes les routes
            allow_origin: ['http://localhost:8090']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Type', 'Authorization']
            max_age: 3600
